server:
  ip: '*'
  port: 8099
  servlet:
    session:
      timeout: 600s
logging:
  path: logs
  file: sshs
spring:
  application:
    name: sshs
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sshs?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  resources:
    staticLocations: 'classpath:'
  security:
    maximum-sessions: 2
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 10MB
mybatis:
  typeAliasesPackage: com.sshs
  mapperLocations: classpath*:*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

toolkit:
  coder:
    path:
      java: /Users/sunyonggang/coder/sshs/src/main/java
      view: /Users/sunyonggang/coder/scaiui/src/main/view