-- 建表脚本-Oracle
-- 自定义查询信息表
CREATE TABLE CORE_CUSTOMISE_QUERY(
  CUSTOMISE_ID  VARCHAR2 (32) NOT NULL,
  USER_CODE  VARCHAR2 (32),
  ORG_CODE  VARCHAR2 (32),
  PAGE_ID  VARCHAR2 (32),
  CUSTOMISE_NAME  VARCHAR2 (200),
  FIELD_CONTENTS  VARCHAR2 (2000),
  FIELD_ADDONS  VARCHAR2 (1000),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT CORE_CUSTOMISE_QUERY PRIMARY KEY (CUSTOMISE_ID)
);
 COMMENT ON TABLE CORE_CUSTOMISE_QUERY IS '核心框架-自定义查询信息表';
 COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.CUSTOMISE_ID IS  '查询ID';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.USER_CODE IS  '用户编码';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.ORG_CODE IS  '机构编码';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.PAGE_ID IS  '页面ID';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.CUSTOMISE_NAME IS  '查询名称';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.FIELD_CONTENTS IS  '条件列';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.FIELD_ADDONS IS  '条件匹配方式';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN CORE_CUSTOMISE_QUERY.UPD_DATE IS  '修改日期';


