-- 建表脚本-Mysql
-- 自定义查询信息表
CREATE TABLE CORE_CUSTOMISE_QUERY(
CUSTOMISE_ID  VARCHAR (32) NOT NULL  COMMENT '查询ID',
USER_CODE  VARCHAR (32) COMMENT '用户编码',
ORG_CODE  VARCHAR (32) COMMENT '机构编码',
PAGE_ID  VARCHAR (32) COMMENT '页面ID',
CUSTOMISE_NAME  VARCHAR (200) COMMENT '查询名称',
FIELD_CONTENTS  VARCHAR (2000) COMMENT '条件列',
FIELD_ADDONS  VARCHAR (1000) COMMENT '条件匹配方式',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (CUSTOMISE_ID)
)
 COMMENT = '核心框架-自定义查询信息表';


