-- 建表脚本-Mysql
-- 机构表
CREATE TABLE SYS_ORG(
ORG_ID  VARCHAR (32) NOT NULL  COMMENT '机构ID',
ORG_CODE  VARCHAR (32) COMMENT '机构编码',
ORG_NAME  VARCHAR (256) COMMENT '机构名称',
ORG_BRIEF  VARCHAR (100) COMMENT '机构简称',
PARENT_ORG_CODE  VARCHAR (32) COMMENT '直接上级机构ID',
ORG_CATEGORY  VARCHAR (10) COMMENT '机构类别:01--机构,02--部门',
ORG_LEVEL  VARCHAR (32) COMMENT '机构层级（树形结构层级）',
ORG_GRADE  VARCHAR (32) COMMENT '机构级别：总行，分行，支行等',
PATH_NAME  VARCHAR (100) COMMENT '中文路径：用‘.’隔开各层级路径名称:.a.b.c.',
STATUS  VARCHAR (10) COMMENT '状态：01--启用,02--停用',
COUNTRY  VARCHAR (10) COMMENT '国家或地区:中国、中国香港、美国等,字典表数据',
EMAIL  VARCHAR (100) COMMENT '联系邮箱',
OFFICE_ADDR  VARCHAR (512) COMMENT '办公地址',
POST  VARCHAR (100) COMMENT '邮政编码',
TEL  VARCHAR (100) COMMENT '联系电话',
CONTACT  VARCHAR (100) COMMENT '联系人',
ORG_FI_NO  VARCHAR (60) COMMENT '金融机构编码（人行）',
ORG_PAY_NO  VARCHAR (60) COMMENT '支付行号（人行）',
ORG_CREDIT_NO  VARCHAR (60) COMMENT '机构信用代码（人行）',
ORG_PERMIT_NO  VARCHAR (60) COMMENT '金融许可证号码（银监）',
ORG_REG_NO  VARCHAR (60) COMMENT '营业执照注册号（工商）',
ORG_ID_NUMBER  VARCHAR (60) COMMENT '组织机构代码证号码',
ORG_TAX_NO  VARCHAR (60) COMMENT '税务登记证号码',
ORG_CREATE_DATE  TIMESTAMP COMMENT '成立日期',
ORG_START_DATE  VARCHAR (10) COMMENT '营业开始时间',
ORG_END_DATE  VARCHAR (10) COMMENT '营业终止时间',
ORG_HEADER  VARCHAR (32) COMMENT '机构负责人',
NODE_NO  VARCHAR (32) COMMENT '网点号',
HIGHER_MNG_ORG  VARCHAR (1000) COMMENT '代管机构：01,02,03',
IS_LEAF  VARCHAR (10) COMMENT '是否最末端',
BUSI_STATUS  VARCHAR (10) COMMENT '营业状态',
AREA_CODE  VARCHAR (10) COMMENT '行政区划代码',
ORDERS  DECIMAL (5) COMMENT '顺序号',
OWN_LINE  VARCHAR (10) COMMENT '所属条线',
VER_NO  DECIMAL (5) COMMENT '版本号',
APPLY_STATUS  VARCHAR (60) COMMENT '审批状态',
OPER_TYPE  VARCHAR (1) COMMENT '操作类型：合并，撤销，转移，修改',
OPER_RELA_ID  VARCHAR (60) COMMENT '关联主键：合并，撤销，转移，修改的关联ID',
APPLY_EMP_NO  VARCHAR (60) COMMENT '申请人',
APPLY_DATE  TIMESTAMP COMMENT '申请日期',
APPLY_REASON  VARCHAR (4000) COMMENT '申请原因',
PROCESS_INSTANCE_ID  VARCHAR (32) COMMENT '审批流ID',
REMARK  VARCHAR (100) COMMENT '备注',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (ORG_ID)
)
 COMMENT = '系统管理-机构表';

-- 岗位表
CREATE TABLE SYS_POST(
POST_ID  VARCHAR (32) NOT NULL  COMMENT '岗位主键',
POST_NO  VARCHAR (32) NOT NULL  COMMENT '岗位编号',
POST_NAME  VARCHAR (50) NOT NULL  COMMENT '岗位名称',
POST_SERIAL  VARCHAR (32) COMMENT '岗位序列:管理序列、专业序列、营销序列、技能序列',
POST_SERIAL_CHILD  VARCHAR (32) COMMENT '岗位子序列',
POST_DESC  VARCHAR (255) COMMENT '岗位描述',
STAND_ORG_CODE  VARCHAR (36) COMMENT '所属标准部门',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (POST_ID)
)
 COMMENT = '系统管理-岗位表';

-- 用户基本信息表
CREATE TABLE SYS_USER(
USER_ID  VARCHAR (32) NOT NULL  COMMENT '主键',
USER_CODE  VARCHAR (32) NOT NULL  COMMENT '用户编号',
USER_NAME  VARCHAR (32) NOT NULL  COMMENT '姓名',
USER_NAME_EN  VARCHAR (32) COMMENT '英文名',
USER_NAME_PY  VARCHAR (50) COMMENT '拼音码',
USER_NAME_FR  VARCHAR (36) COMMENT '曾用名',
ORG_CODE  VARCHAR (36) COMMENT '机构编号:到具体的部门、支行和二级中心',
POST_NO  VARCHAR (32) COMMENT '岗位',
USER_SEX  VARCHAR (2) COMMENT '性别:1－男性，2－女性，9－未说明性别',
NATIONALITY  VARCHAR (3) COMMENT '国籍',
ETHNIC  VARCHAR (50) COMMENT '民族:01=汉族',
NATIVE_PLACE  VARCHAR (100) COMMENT '籍贯',
BIRTH_PLACE  VARCHAR (50) COMMENT '出生地',
BIRTH_DATE  TIMESTAMP COMMENT '出生日期',
ID_DECIMAL  VARCHAR (20) COMMENT '身份证号码',
PHOTO_ID  VARCHAR (100) COMMENT '证件照',
JOIN_DATE  TIMESTAMP COMMENT '入职日期',
STATUS  VARCHAR (10) COMMENT '用户状态:0-无效，1-有效',
TELLER_ID  VARCHAR (32) COMMENT '柜员编号',
RESIDENTIAL_ADDRESS  VARCHAR (1000) COMMENT '现居住地址',
MOBILE_PHONE  VARCHAR (32) COMMENT '手机',
REMARK  VARCHAR (250) COMMENT '备注',
PASSWORD  VARCHAR (200) COMMENT '密码',
SALT  VARCHAR (32) COMMENT '盐（密码）',
ONLINE_STATUS  VARCHAR (10) COMMENT '在线状态:在线、离线、锁定',
IP_ADDR  VARCHAR (60) COMMENT 'IP地址',
USER_THEME  VARCHAR (32) COMMENT '用户皮肤',
PD_COUNT  VARCHAR (32) COMMENT '密码输入次数',
PD_MODTIME  VARCHAR (32) COMMENT '密码修改时间',
PD_LOCKTIME  VARCHAR (32) COMMENT '密码锁定时间',
LAST_SIGNON_TIME  TIMESTAMP COMMENT '最后一次登陆时间',
LAST_SIGNOUT_TIME  TIMESTAMP COMMENT '最后一次退出时间',
LEGAL_ORG  VARCHAR (50) COMMENT '法人机构编号',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (USER_ID)
)
 COMMENT = '系统管理-用户基本信息表';

-- 用户扩展信息表
CREATE TABLE SYS_USER_EXT(
USER_ID  VARCHAR (32) NOT NULL  COMMENT '主键',
POLITICAL_STATUS  VARCHAR (10) COMMENT '政治面貌:团员、党员、其他党派人士、无党派',
PARTY_TIME  VARCHAR (10) COMMENT '入党时间',
MARITAL_STATUS  VARCHAR (10) COMMENT '婚姻状况:10-未婚；20-已婚；21-离婚；40-丧偶；',
BLOOD_TYPE  VARCHAR (10) COMMENT '血型:A型、B型、AB型、O型、未知血型',
ENGLISH_LEVEL  VARCHAR (10) COMMENT '英语等级',
COMPUTER_LEVEL  VARCHAR (10) COMMENT '计算机等级',
WORK_TIME  VARCHAR (50) COMMENT '参加工作年月',
INDUCTION_TYPE  VARCHAR (10) COMMENT '入职类型:社会招录、资源性人才引进、系统内调入、系统外调入',
EMPLOY_WAY  VARCHAR (10) COMMENT '用工方式:合同制员工
派遣制员工
实习员工',
EMP_STATUS  VARCHAR (10) COMMENT '员工状态:在职在岗
在编不在岗的
离岗退养
转非
退休
死亡',
JOIN_DATE  TIMESTAMP COMMENT '入职日期',
HEIGHT  DECIMAL (5,2) COMMENT '身高',
WEIGHT  DECIMAL (5,2) COMMENT '体重',
CHILD_NUM  DECIMAL (2) COMMENT '子女人数',
HEALTH_STATE  VARCHAR (10) COMMENT '健康状况:健康
一般
慢性疾病
生理缺陷
残废
较弱',
HIGHEST_EDU  VARCHAR (2) COMMENT '最高学历:中专、高中、大专、专科、本科、研究生（硕士）、研究生（博士）',
HIGHEST_DEGREE  VARCHAR (2) COMMENT '最高学位:0-其他；1-名誉博士；
2-博士；
3-硕士；
4-学士；
9-未知。',
CONTACT_ADDRESS  VARCHAR (1000) COMMENT '通讯地址',
POSTCODE_CONTACT  VARCHAR (32) COMMENT '通讯地址邮编',
RESIDENTIAL_ADDRESS  VARCHAR (1000) COMMENT '现居住地址',
POSTCODE_RESIDENTIAL  VARCHAR (32) COMMENT '现居住地邮编',
DOMICILE_ADDRESS  VARCHAR (1000) COMMENT '户籍所在地',
POSTCODE_DOMICILE  VARCHAR (32) COMMENT '户籍所在地邮编',
HOUSEHOLD_REG  VARCHAR (1) COMMENT '户籍类型:城镇,非城镇',
EMAIL  VARCHAR (64) COMMENT '电子邮箱',
MOBILE_PHONE  VARCHAR (32) COMMENT '手机',
HOME_TELPHONE  VARCHAR (32) COMMENT '家庭电话',
EMERGENCY_CONTACT  VARCHAR (32) COMMENT '紧急联系人',
EMERGENCY_CONTACT_PHONE  VARCHAR (32) COMMENT '紧急联系人手机',
QQ  VARCHAR (32) COMMENT 'QQ号',
WECHAT  VARCHAR (32) COMMENT '微信号',
REMARK  VARCHAR (250) COMMENT '备注',
LEGAL_ORG  VARCHAR (50) COMMENT '法人机构编号',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (USER_ID)
)
 COMMENT = '系统管理-用户扩展信息表';

-- 菜单表
CREATE TABLE SYS_MENU(
MENU_CODE  VARCHAR (32) NOT NULL  COMMENT '菜单编码',
MENU_NAME  VARCHAR (100) COMMENT '菜单名称',
MENU_TYPE  VARCHAR (2) COMMENT '菜单类型:0-节点，1-功能',
MENU_URL  VARCHAR (256) COMMENT '菜单路径URL',
PARENT_MENU_CODE  VARCHAR (32) COMMENT '所属父菜单',
MENU_MODULE  VARCHAR (32) COMMENT '所属模块',
IS_RELATIVE_PATH  VARCHAR (10) COMMENT '是否相对路径',
MENU_LEVEL  DECIMAL (5) COMMENT '菜单层次',
MENU_SEQ  DECIMAL(5) COMMENT '同级菜单顺序号',
MENU_ICON  VARCHAR (100) COMMENT '菜单图标路径/或样式',
MENU_ICONA  VARCHAR (100) COMMENT '菜单激活图标路径/或样式',
IS_VISIBLE  VARCHAR (10) COMMENT '是否可视:1-是,0-否',
OPEN_MODE  VARCHAR (20) COMMENT '主窗口打开、弹出窗口打开',
MENU_TIP  VARCHAR (100) COMMENT '提示信息',
IS_START  VARCHAR (10) COMMENT '是否启用:1-是,0-否',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (MENU_CODE)
)
 COMMENT = '系统管理-菜单表';

-- 菜单国际化表
CREATE TABLE SYS_MENU_I18N(
I18N_ID  VARCHAR (32) NOT NULL  COMMENT 'I18N_ID',
MENU_CODE  VARCHAR (32) COMMENT '菜单编码',
LANGUAGE  VARCHAR (10) COMMENT '语言',
COUNTRY  VARCHAR (10) COMMENT '国家',
MENU_LABEL  VARCHAR (100) COMMENT '菜单显示（中文）',
MENU_TIP  VARCHAR (100) COMMENT '提示信息',
IS_START  VARCHAR (10) COMMENT '是否启用:01--是,02--否',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (I18N_ID)
)
 COMMENT = '系统管理-菜单国际化表';

-- 角色表
CREATE TABLE SYS_ROLE(
ROLE_CODE  VARCHAR (32) NOT NULL  COMMENT '角色编码',
ROLE_NAME  VARCHAR (100) COMMENT '角色名称',
REMARK  VARCHAR (1000) COMMENT '角色描述',
ROLE_LEVEL  VARCHAR (10) COMMENT '角色级别:对应机构级别',
STATUS  VARCHAR (10) COMMENT '状态:01--启用，02--停用',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (ROLE_CODE)
)
 COMMENT = '系统管理-角色表';

-- 用户角色对照表
CREATE TABLE SYS_USER_ROLE(
USER_ROLE_ID  VARCHAR (32) NOT NULL  COMMENT 'ID',
USER_CODE  VARCHAR (32) COMMENT '用户编号',
ROLE_CODE  VARCHAR (32) COMMENT '角色编号',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (USER_ROLE_ID)
)
 COMMENT = '系统管理-用户角色对照表';

-- 角色权限表
CREATE TABLE SYS_AUTHORIZE(
AUTHORIZE_ID  VARCHAR (32) NOT NULL  COMMENT '权限ID',
RESOURCE_ID  VARCHAR (32) NOT NULL  COMMENT '资源ID(包括菜单ID和按钮ID)',
RESOURCE_NAME  VARCHAR (100) COMMENT '资源名称',
ROLE_CODE  VARCHAR (32) COMMENT '角色编号',
RESOURCE_TYPE  VARCHAR (10) COMMENT '资源类型:01-菜单,02-按钮',
AUTHORIZE_TYPE  VARCHAR (2) COMMENT '授权类型:01-操作,02-授权,03-全部',
DATA_AUTH_TYPE  VARCHAR (10) COMMENT '权限级别，对应机构级别（RESOURCE_TYPE为01且AUTHORIZE_TYPE为01或03时该字段可用）',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (AUTHORIZE_ID)
)
 COMMENT = '系统管理-角色权限表';

-- 数据字典表
CREATE TABLE SYS_DICTIONARIES(
DICT_ID  VARCHAR (32) NOT NULL  COMMENT 'ID',
PARENT_ID  VARCHAR (32) COMMENT '上级ID',
DICT_TYPE  VARCHAR (1) COMMENT '类型:0-分类,1-字典项,2-字典子项,3-字典码值',
DICT_CODE  VARCHAR (32) COMMENT '代码',
DICT_NAME  VARCHAR (100) COMMENT '名称',
DICT_DESC  VARCHAR (100) COMMENT '描述',
STATUS  VARCHAR (32) COMMENT '状态1:有效0:无效',
SORT_NO  DECIMAL (10) COMMENT '排序',
IS_SYSTEM  VARCHAR (2) COMMENT '是否系统类1:系统类0:业务类',
MODULE  VARCHAR (10) COMMENT '模块',
LEGAL_ORG  VARCHAR (32) COMMENT '法人行社',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (DICT_ID)
)
 COMMENT = '系统管理-数据字典表';

-- 数据字典国际化表
CREATE TABLE SYS_DICTIONARIES_I18N(
I18N_ID  VARCHAR (32) NOT NULL  COMMENT 'I18N_ID',
DICT_ID  VARCHAR (32) COMMENT 'ID',
DICT_CODE  VARCHAR (32) COMMENT '代码',
LANGUAGE  VARCHAR (10) COMMENT '语言',
COUNTRY  VARCHAR (10) COMMENT '国家',
DICT_NAME  VARCHAR (100) COMMENT '名称',
DICT_DESC  VARCHAR (100) COMMENT '描述',
STATUS  VARCHAR (32) COMMENT '状态1:有效0:无效',
LEGAL_ORG  VARCHAR (32) COMMENT '法人行社',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (I18N_ID)
)
 COMMENT = '系统管理-数据字典国际化表';

-- 代码生成表
CREATE TABLE SYS_CODER(
CODER_ID  VARCHAR (32) NOT NULL  COMMENT '代码生成ID',
TITLE  VARCHAR (100) COMMENT '描述',
MODEL_NAME  VARCHAR (200) COMMENT '模块名',
MODEL_NAME_CN  VARCHAR (200) COMMENT '模块名(中文)',
PACKAGE_NAME  VARCHAR (200) COMMENT '包名',
CLASS_NAME  VARCHAR (100) COMMENT '类名',
FUNCTION_NAME  VARCHAR (100) COMMENT '功能名称',
TABLE_NAME  VARCHAR (50) COMMENT '表名',
TABLE_COMMENT  VARCHAR (200) COMMENT '表描述',
FIELDS  BLOB COMMENT '字段列表',
CODER_TYPE  VARCHAR (10) COMMENT '类型(单表，树形，主从表)',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (CODER_ID)
)
 COMMENT = '系统管理-代码生成表';


