-- 建表脚本-Oracle
-- 代码生成表
CREATE TABLE TOO_CODER(
  CODER_ID  VARCHAR2 (32) NOT NULL,
  TITLE  VARCHAR2 (100),
  MODEL_NAME  VARCHAR2 (200),
  MODEL_NAME_CN  VARCHAR2 (200),
  PACKAGE_NAME  VARCHAR2 (200),
  CLASS_NAME  VARCHAR2 (100),
  FUNCTION_NAME  VARCHAR2 (100),
  TABLE_NAME  VARCHAR2 (50),
  TABLE_COMMENT  VARCHAR2 (200),
  FIELDS  BLOB,
  CODER_TYPE  VARCHAR2 (10),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT TOO_CODER PRIMARY KEY (CODER_ID)
);
 COMMENT ON TABLE TOO_CODER IS '开发辅助-代码生成表';
 COMMENT ON COLUMN TOO_CODER.CODER_ID IS  '代码生成ID';
COMMENT ON COLUMN TOO_CODER.TITLE IS  '描述';
COMMENT ON COLUMN TOO_CODER.MODEL_NAME IS  '模块名';
COMMENT ON COLUMN TOO_CODER.MODEL_NAME_CN IS  '模块名(中文)';
COMMENT ON COLUMN TOO_CODER.PACKAGE_NAME IS  '包名';
COMMENT ON COLUMN TOO_CODER.CLASS_NAME IS  '类名';
COMMENT ON COLUMN TOO_CODER.FUNCTION_NAME IS  '功能名称';
COMMENT ON COLUMN TOO_CODER.TABLE_NAME IS  '表名';
COMMENT ON COLUMN TOO_CODER.TABLE_COMMENT IS  '表描述';
COMMENT ON COLUMN TOO_CODER.FIELDS IS  '字段列表';
COMMENT ON COLUMN TOO_CODER.CODER_TYPE IS  '类型(单表，树形，主从表)';
COMMENT ON COLUMN TOO_CODER.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN TOO_CODER.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN TOO_CODER.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN TOO_CODER.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN TOO_CODER.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN TOO_CODER.UPD_DATE IS  '修改日期';


