-- 建表脚本-DB2
-- 代码生成表
CREATE TABLE TOO_CODER(
  CODER_ID  VARCHAR (32) NOT NULL,
  TITLE  VARCHAR (100),
  MODEL_NAME  VARCHAR (200),
  MODEL_NAME_CN  VARCHAR (200),
  PACKAGE_NAME  VARCHAR (200),
  CLASS_NAME  VARCHAR (100),
  FUNCTION_NAME  VARCHAR (100),
  TABLE_NAME  VARCHAR (50),
  TABLE_COMMENT  VARCHAR (200),
  FIELDS  BLOB,
  CODER_TYPE  VARCHAR (10),
  CRT_USER_CODE  VARCHAR (32),
  CRT_ORG_CODE  VARCHAR (32),
  CRT_DATE  TIMESTAMP,
  UPD_USER_CODE  VARCHAR (32),
  UPD_ORG_CODE  VARCHAR (32),
  UPD_DATE  TIMESTAMP,
CONSTRAINT TOO_CODER PRIMARY KEY (CODER_ID)
) IN TS_PAMS_PROD INDEX IN TS_PAMS_PROD_IND;
 COMMENT ON TABLE TOO_CODER IS '开发辅助-代码生成表';
 COMMENT ON TOO_CODER(
CODER_ID IS  '代码生成ID',
TITLE IS  '描述',
MODEL_NAME IS  '模块名',
MODEL_NAME_CN IS  '模块名(中文)',
PACKAGE_NAME IS  '包名',
CLASS_NAME IS  '类名',
FUNCTION_NAME IS  '功能名称',
TABLE_NAME IS  '表名',
TABLE_COMMENT IS  '表描述',
FIELDS IS  '字段列表',
CODER_TYPE IS  '类型(单表，树形，主从表)',
CRT_USER_CODE IS  '创建人',
CRT_ORG_CODE IS  '创建机构',
CRT_DATE IS  '创建日期',
UPD_USER_CODE IS  '修改人',
UPD_ORG_CODE IS  '修改机构',
UPD_DATE IS  '修改日期'
);
COMMIT;

