-- 建表脚本-Mysql
-- 索引目录表
CREATE TABLE DEV_INDEX_PATH(
PATH_ID  varchar(32) NOT NULL  COMMENT '路径编号',
PATH_NAME  varchar(200) COMMENT '路径名称',
PARENT_ID  varchar(32) COMMENT '上级路径',
PATH_TEXT  varchar(500) COMMENT '全路径',
PATH_MODULE  varchar(500) COMMENT '功能模块',
PATH_LEVEL  DECIMAL(5) COMMENT '路径层级',
PATH_ICONS  varchar(300) COMMENT '图标',
PATH_ORDER  DECIMAL(5) COMMENT '路径排序',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (PATH_ID)
)
 COMMENT = '开发中心-索引目录表';

-- 数据源表
CREATE TABLE DEV_DATA_SOURCE(
SOURCE_ID  varchar(32) NOT NULL  COMMENT '数据源编号',
SOURCE_NAME  varchar(200) COMMENT '数据源名称',
SOURCE_DESC  varchar(500) COMMENT '数据源描述',
SOURCE_TYPE  varchar(2) COMMENT '数据源类型（0-关系型数据源，1-文件数据源，2-服务型数据源）',
DRIVE_TYPE  varchar(50) COMMENT '驱动程序类型（mysql、Db2……，excel、txt）',
DRIVE_CLASS  varchar(100) COMMENT '驱动程序类',
CONN_URL  varchar(500) COMMENT '连接URL',
DB_NAME  varchar(255) COMMENT '数据库名',
USER_NAME  varchar(50) COMMENT '用户名',
PASSWORD  varchar(100) COMMENT '密码',
SRC_CHARACTER  varchar(100) COMMENT '数据源字符集',
GOAL_CHARACTER  varchar(100) COMMENT '数据源目标字符集',
VERIFY_TYPE  varchar(1) COMMENT '验证类型（0-静态1-动态）',
MAX_CONN  DECIMAL(11) COMMENT '最大连接数',
CHECK_TYPE  varchar(1) COMMENT '检验类型',
SENTERNCE  varchar(300) COMMENT '检验语句',
TRAN_LEVEL  varchar(1) COMMENT '事务隔离级别',
REF_ID  varchar(300) COMMENT '引用标识符',
STATUS  varchar(1) COMMENT '状态（0-创建，1-存草稿，2-分享，3-发布）',
INDEX_PATH  varchar(32) COMMENT '索引路径',
ICONS  varchar(300) COMMENT '图标',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (SOURCE_ID)
)
 COMMENT = '开发中心-数据源表';

-- 数据表表
CREATE TABLE DEV_DATA_TABLE(
TABLE_ID  VARCHAR (32) NOT NULL  COMMENT '表编号',
SOURCE_ID  varchar(32) NOT NULL  COMMENT '数据源编号',
SOURCE_NAME  varchar(255) NOT NULL  COMMENT '数据源名称',
TABLE_NAME  VARCHAR (255) COMMENT '表名称',
TABLE_DESC  VARCHAR (255) COMMENT '表描述',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (TABLE_ID)
)
 COMMENT = '开发中心-数据表表';

-- 数据源列表
CREATE TABLE DEV_DATA_COLUMN(
COLUMN_ID  VARCHAR (32) NOT NULL  COMMENT '列编号',
TABLE_ID  VARCHAR (32) NOT NULL  COMMENT '表编号',
SOURCE_ID  varchar(32) NOT NULL  COMMENT '数据源编号',
TABLE_NAME  VARCHAR (100) COMMENT '表名称',
TABLE_DESC  VARCHAR (255) COMMENT '表描述',
COLUMN_NAME  VARCHAR (100) COMMENT '列名称',
COLUMN_DESC  VARCHAR (255) COMMENT '列描述',
COLUMN_TYPE  VARCHAR (50) COMMENT '列类型',
COLUMN_ORDER  DECIMAL(5) COMMENT '字段顺序',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (COLUMN_ID)
)
 COMMENT = '开发中心-数据列表';

-- 参数信息表
CREATE TABLE DEV_PARAM_PARAMETER(
PARAMETER_ID  VARCHAR (32) NOT NULL  COMMENT '参数编号',
PARAMETER_NAME  VARCHAR (200) NOT NULL  COMMENT '参数名称',
PARAMETER_DESC  VARCHAR (200) COMMENT '参数描述',
PARAMETER_TYPE  VARCHAR (2) COMMENT '参数类型(0-全局参数 1-私有参数)',
DATA_TYPE  VARCHAR (2) COMMENT '数据类型，0字符串，1整形 ，2浮点型，3日期，4时间，5日期时间',
COMPONENT_TYPE  VARCHAR (3) COMMENT '控件类型：0文本框，1勾选框，2下拉框，3树形对话框，4日期时间控件',
COMPONENT_WIDTH  DECIMAL(5) COMMENT '控件宽度',
COMPONENT_HEIGHT  DECIMAL(5) COMMENT '控件高度',
CONTENT_WIDTH  DECIMAL(5) COMMENT '控件下拉框宽度',
CONTENT_HEIGHT  DECIMAL(5) COMMENT '控件下拉框高度',
DEFAULT_VALUE  VARCHAR (300) COMMENT '默认值',
DEFAULT_EXPR  VARCHAR (300) COMMENT '默认值表达式',
SELECTED_VALUE  VARCHAR (200) COMMENT '备选值',
SELECTED_EXPR  VARCHAR (500) COMMENT '备选值表达式',
SELECTED_VAL_TYPE  VARCHAR (2) COMMENT '备选值类型',
LINK_TABLE  VARCHAR (200) COMMENT '参数所属表',
STATUS  varchar(1) COMMENT '状态（0-创建，1-存草稿，2-分享，3-发布）',
INDEX_PATH  varchar(32) COMMENT '索引路径',
ICONS  varchar(300) COMMENT '图标',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (PARAMETER_ID)
)
 COMMENT = '开发中心-参数信息表';

-- 查询主信息表
CREATE TABLE DEV_INQUIRY_MAIN(
INQUIRY_ID  VARCHAR (32) NOT NULL  COMMENT '查询编号',
INQUIRY_NAME  VARCHAR (200) NOT NULL  COMMENT '查询名称',
INQUIRY_TYPE  VARCHAR (2) COMMENT '查询类型（00-sql，01-可视化，10-excel，11-txt，20-服务）',
SOURCE_ID  varchar(32) COMMENT '数据源编号',
ORIG_SQL  VARCHAR (10000) COMMENT '原始SQL(文件名、服务名)',
EXECUTE_SQL  VARCHAR (10000) COMMENT '执行SQL（文件路径、服务信息）',
STATUS  VARCHAR (1) COMMENT '状态（0-创建，1-存草稿，2-分享，3-发布）',
INDEX_PATH  varchar(32) COMMENT '索引路径',
ICONS  varchar(300) COMMENT '图标',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (INQUIRY_ID)
)
 COMMENT = '开发中心-查询主信息表';

-- 查询表信息表
CREATE TABLE DEV_INQUIRY_TABLE(
TABLE_ID  VARCHAR (32) NOT NULL  COMMENT '查询表编号',
INQUIRY_ID  VARCHAR (32) NOT NULL  COMMENT '查询编号',
TABLE_NAME  VARCHAR (100) NOT NULL  COMMENT '表名称',
TABLE_ALIAS  VARCHAR (100) COMMENT '表别名',
TABLE_DESC  VARCHAR (200) COMMENT '表描述',
TABLE_ORDER  DECIMAL(5) COMMENT '表顺序',
TABLE_TYPE  VARCHAR (20) COMMENT '表类型',
TABLE_SCHEMA  VARCHAR (50) COMMENT '所属表别名',
REL_TABLE  VARCHAR (100) COMMENT '关联表名称',
REL_TYPE  VARCHAR (5) COMMENT '关联方式（0-内关联，1-左关联，2-右关联）',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (TABLE_ID)
)
 COMMENT = '开发中心-查询表信息表';

-- 查询输出列信息表
CREATE TABLE DEV_INQUIRY_COLUMN(
COLUMN_ID  VARCHAR (32) NOT NULL  COMMENT '列编号',
INQUIRY_ID  VARCHAR (32) NOT NULL  COMMENT '查询编号',
COLUMN_NAME  VARCHAR (100) COMMENT '字段名称',
COLUMN_ALIAS  VARCHAR (100) COMMENT '字段别名',
COLUMN_DESC  VARCHAR (200) COMMENT '字段描述',
COLUMN_ORDER  DECIMAL(5) COMMENT '字段顺序',
COLUMN_TYPE  VARCHAR (20) COMMENT '字段类型',
COLUMN_HIDDEN  VARCHAR (2) COMMENT '字段隐藏（1-隐藏，0-显示）',
TABLE_ALIAS  VARCHAR (1) COMMENT '所属表别名',
IS_NUMBER  VARCHAR (1) COMMENT '是否数字类型（1-是，0-否）',
IS_AGGREGATE  VARCHAR (1) COMMENT '是否聚合函数0否1是',
AGGREGATE_TYPE  VARCHAR (1) COMMENT '聚合函数类型0一般1特殊',
AGGREGATE  VARCHAR (100) COMMENT '聚合函数',
IS_GROUP_COLUMN  VARCHAR (1) COMMENT '是否分组字段（0-否，1-是）',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (COLUMN_ID)
)
 COMMENT = '开发中心-查询输出列信息表';

-- 查询条件信息表
CREATE TABLE DEV_INQUIRY_CONDITION(
COND_ID  VARCHAR (32) NOT NULL  COMMENT '条件编号',
INQUIRY_ID  VARCHAR (32) NOT NULL  COMMENT '查询编号',
TABLE_ID  VARCHAR (32) COMMENT '表编号',
COND_TYPE  VARCHAR (2) COMMENT '条件类型（0-常量筛选条件，1-关联条件，2-参数条件，3-权限过滤）',
COND_PREFIX  VARCHAR (20) COMMENT '表达式前缀',
COND_COLUMN  VARCHAR (100) COMMENT '条件表达式',
COND_SYMBOL  VARCHAR (20) COMMENT '条件表达式运算符',
COND_VALUE  VARCHAR (200) COMMENT '条件表达式值',
COND_POSTFIX  VARCHAR (20) COMMENT '表达式后缀',
COND_ORDER  DECIMAL(5) COMMENT '条件排序',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (COND_ID)
)
 COMMENT = '开发中心-查询条件信息表';

-- 图表定义主表
CREATE TABLE DEV_REPORT_DEFINE(
CHARTS_ID  VARCHAR (32) NOT NULL  COMMENT '图表编号',
CHARTS_TYPE  VARCHAR (50) NOT NULL  COMMENT '图表类型',
CHARTS_NAME  VARCHAR (200) COMMENT '图表名称',
CHARTS_CATEGORY  VARCHAR (32) COMMENT '图表分类',
ICONS  VARCHAR (300) COMMENT '图标',
CHARTS_DIM_MIN  DECIMAL(5) COMMENT '维度最小数',
CHARTS_DIM_MAX  DECIMAL(5) COMMENT '维度最大数',
CHARTS_MEA_MIN  DECIMAL(5) COMMENT '度量最小数',
CHARTS_MEA_MAX  DECIMAL(5) COMMENT '度量最大数',
CHARTS_DATE_NUM  DECIMAL(5) COMMENT '日期数量',
CHARTS_PLACE_NUM  DECIMAL(5) COMMENT '地理数量',
COMPONENT_NAME  VARCHAR (100) COMMENT '组件名称',
CHART_ORDER  INT COMMENT '排序',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (CHARTS_ID)
)
 COMMENT = '开发中心-图表定义主表';

-- 图表定义_国际化表
CREATE TABLE DEV_REPORT_DEFINE_I18N(
I18N_ID  VARCHAR (32) NOT NULL  COMMENT '国际化编号',
CHARTS_ID  VARCHAR (32) NOT NULL  COMMENT '图表编号',
LANGUAGE  VARCHAR (10) COMMENT '语言',
COUNTRY  VARCHAR (10) COMMENT '国家',
CHARTS_NAME  VARCHAR (200) COMMENT '图表名称',
CHARTS_COMMENT  VARCHAR (500) COMMENT '图表说明',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (I18N_ID)
)
 COMMENT = '开发中心-图表定义国际化表';

-- 图表定义属性表
CREATE TABLE DEV_REPORT_ATTR_DEF(
CHARTS_ATTR_ID  VARCHAR (32) NOT NULL  COMMENT '图表属性编号',
CHARTS_ID  VARCHAR (32) COMMENT '图表编号',
PARENT_ATTR_ID  VARCHAR (32) COMMENT '上级属性ID',
CHARTS_ATTR_TYPE  VARCHAR (20) COMMENT '图表属性类型(String,Object,ARRAY)',
CHARTS_ATTR_NAME  VARCHAR (100) COMMENT '图表属性名称',
CHARTS_ATTR_VALUE  VARCHAR (200) COMMENT '图表属性值',
CHARTS_ATTR_DESC  VARCHAR (200) COMMENT '图表属性描述',
CHARTS_ATTR_ORDER  DECIMAL(5) COMMENT '属性排序',
COMPONENT_TYPE  VARCHAR (50) COMMENT '组件类型',
COMPONENT_OPTIONS  VARCHAR (500) COMMENT '可选值',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (CHARTS_ATTR_ID)
)
 COMMENT = '开发中心-图表定义属性表';

-- 图表定义属性_国际化表
CREATE TABLE DEV_REPORT_ATTR_I18N(
I18N_ID  VARCHAR (32) NOT NULL  COMMENT '图表属性编号',
CHARTS_ATTR_ID  VARCHAR (32) NOT NULL  COMMENT '图表属性编号',
LANGUAGE  VARCHAR (10) COMMENT '语言',
COUNTRY  VARCHAR (10) COMMENT '国家',
CHARTS_ATTR_DESC  VARCHAR (200) COMMENT '图表属性描述',
COMPONENT_OPTIONS  VARCHAR (500) COMMENT '可选值',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (I18N_ID)
)
 COMMENT = '开发中心-图表定义属性国际化表';

-- 图表定义绑定表
CREATE TABLE DEV_REPORT_BIND_DEF(
CHARTS_BIND_ID  VARCHAR (32) NOT NULL  COMMENT '绑定编号',
CHARTS_ID  VARCHAR (32) COMMENT '图表编号',
BIND_NAME  VARCHAR (100) COMMENT '绑定名称',
BIND_TYPE  VARCHAR (20) COMMENT '绑定数据类型（0-任意，1-数字）',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (CHARTS_BIND_ID)
)
 COMMENT = '开发中心-图表定义绑定表';

-- 图表信息主表
CREATE TABLE DEV_REPORT_INFO(
REPORT_ID  VARCHAR (32) NOT NULL  COMMENT '报表编号',
REPORT_NAME  VARCHAR (200) COMMENT '报表名称',
REPORT_DESC  VARCHAR (200) COMMENT '报表描述',
CHARTS_ID  VARCHAR (32) COMMENT '图表编号',
CHARTS_TYPE  VARCHAR (2) COMMENT '图表类型',
INQUIRY_ID  VARCHAR (32) COMMENT '查询编号',
REPORT  text COMMENT '报表内容（固定报表）',
CHARTS_DIM_MIN  DECIMAL(5) COMMENT '维度最小数',
CHARTS_DIM_MAX  DECIMAL(5) COMMENT '维度最大数',
CHARTS_MEA_MIN  DECIMAL(5) COMMENT '度量最小数',
CHARTS_MEA_MAX  DECIMAL(5) COMMENT '度量最大数',
STATUS  VARCHAR (1) COMMENT '状态（0-创建，1-存草稿，2-分享，3-发布）',
INDEX_PATH  varchar(32) COMMENT '索引路径',
ICONS  varchar(300) COMMENT '图标',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (REPORT_ID)
)
 COMMENT = '开发中心-图表信息主表';

-- 图表信息属性表
CREATE TABLE DEV_REPORT_ATTR_INFO(
REPORT_ATTR_ID  VARCHAR (32) NOT NULL  COMMENT '报表属性编号',
REPORT_ID  VARCHAR (32) NOT NULL  COMMENT '报表编号',
CHARTS_ATTR_ID  VARCHAR (32) COMMENT '图表属性编号',
CHARTS_ID  VARCHAR (32) COMMENT '图表编号',
PARENT_ATTR_ID  VARCHAR (32) COMMENT '上级属性ID',
CHARTS_ATTR_TYPE  VARCHAR (20) COMMENT '图表属性类型(String,Object,ARRAY)',
CHARTS_ATTR_NAME  VARCHAR (100) COMMENT '图表属性名称',
CHARTS_ATTR_VALUE  VARCHAR (200) COMMENT '图表属性值',
CHARTS_ATTR_DESC  VARCHAR (200) COMMENT '图表属性描述',
COMPONENT_TYPE  VARCHAR (50) COMMENT '组件类型',
COMPONENT_OPTIONS  VARCHAR (500) COMMENT '可选值',
CHARTS_ATTR_ORDER  DECIMAL(5) COMMENT '属性排序',
IS_CUSTOM  VARCHAR (1) COMMENT '是否自定义',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (REPORT_ATTR_ID)
)
 COMMENT = '开发中心-图表信息属性表';

-- 图表信息绑定表
CREATE TABLE DEV_REPORT_BIND_INFO(
REPORT_BIND_ID  VARCHAR (32) NOT NULL  COMMENT '报表绑定编号',
REPORT_ID  VARCHAR (32) NOT NULL  COMMENT '报表编号',
CHARTS_BIND_ID  VARCHAR (32) NOT NULL  COMMENT '图表绑定编号',
CHARTS_ID  VARCHAR (32) COMMENT '图表编号',
BIND_NAME  VARCHAR (100) COMMENT '绑定名称',
BIND_TYPE  VARCHAR (20) COMMENT '绑定数据类型（0-任意，1-数字）',
BIND_VALUE  VARCHAR (200) COMMENT '绑定值',
BIND_DESC  VARCHAR (200) COMMENT '绑定值描述',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (REPORT_BIND_ID)
)
 COMMENT = '开发中心-图表定义绑定表';

-- 图表输出列信息表
CREATE TABLE DEV_REPORT_COLUMN(
REPORT_COLUMN_ID  VARCHAR (32) NOT NULL  COMMENT '报表列编号',
REPORT_ID  VARCHAR (32) NOT NULL  COMMENT '报表编号',
INQUIRY_ID  VARCHAR (32) NOT NULL  COMMENT '查询编号',
COLUMN_NAME  VARCHAR (100) COMMENT '字段名称',
COLUMN_ALIAS  VARCHAR (100) COMMENT '字段别名',
COLUMN_DESC  VARCHAR (200) COMMENT '字段描述',
COLUMN_ORDER  DECIMAL(5) COMMENT '字段顺序',
COLUMN_TYPE  VARCHAR (20) COMMENT '字段类型',
COLUMN_BIND  VARCHAR (50) COMMENT '字段绑定(row:行，col：列，value：值)',
IS_NUMBER  VARCHAR (1) COMMENT '是否度量（1-是，0-否）',
IS_AGGREGATE  VARCHAR (1) COMMENT '是否聚合函数0否1是',
AGGREGATE_TYPE  VARCHAR (1) COMMENT '聚合函数类型0一般1特殊',
AGGREGATE  VARCHAR (100) COMMENT '聚合函数',
IS_GROUP_COLUMN  VARCHAR (1) COMMENT '是否分组字段（0-否，1-是）',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (REPORT_COLUMN_ID)
)
 COMMENT = '开发中心-图表输出列信息表';

-- 图表信息参数表
CREATE TABLE DEV_REPORT_PARAM_INFO(
REPORT_PARAM_ID  VARCHAR (32) NOT NULL  COMMENT '报表参数编号',
REPORT_ID  VARCHAR (32) NOT NULL  COMMENT '报表编号',
PARAMETER_ID  VARCHAR (32) COMMENT '参数编号',
COLUMN_ALIAS  VARCHAR (100) COMMENT '字段别名',
INQUIRY_ID  VARCHAR (32) COMMENT '查询编号',
COND_TYPE  VARCHAR (2) COMMENT '条件类型（0-常量筛选条件，1-关联条件，2-参数条件，3-权限过滤）',
COND_PREFIX  VARCHAR (20) COMMENT '表达式前缀',
COND_COLUMN  VARCHAR (100) COMMENT '条件表达式',
COND_SYMBOL  VARCHAR (20) COMMENT '条件表达式运算符',
COND_VALUE  VARCHAR (200) COMMENT '条件表达式值',
COND_POSTFIX  VARCHAR (20) COMMENT '表达式后缀',
COND_REQUIRED  VARCHAR (10) COMMENT '是否必输',
ICONS  varchar(300) COMMENT '图标',
COMPONENT_TYPE  VARCHAR (50) COMMENT '组件类型',
COMPONENT_OPTIONS  VARCHAR (500) COMMENT '可选值',
CHARTS_ATTR_ORDER  DECIMAL(5) COMMENT '属性排序',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (REPORT_PARAM_ID)
)
 COMMENT = '开发中心-图表信息参数表';

-- 分析布局定义表
CREATE TABLE DEV_ANALYSIS_LAYOUT_DEF(
LAYOUT_ID  VARCHAR (32) NOT NULL  COMMENT '布局编号',
ITEM_COUNT  DECIMAL(5) NOT NULL  COMMENT '容纳数量',
WIDTH  VARCHAR (20) COMMENT '容器宽度',
HEIGHT  VARCHAR (20) COMMENT '容器高度',
FLEX_DIRECTION  VARCHAR (50) COMMENT '项目的排列方向(row | row-reverse | column | column-reverse;)',
FLEX_WRAP  VARCHAR (50) COMMENT '项目换行方式（nowrap | wrap | wrap-reverse;）',
JUSTIFY_CONTENT  VARCHAR (50) COMMENT '项目水平对齐方式（flex-start | flex-end | center | space-between | space-around;）',
ALIGN_ITEMS  VARCHAR (50) COMMENT '项目垂直对齐方式（flex-start | flex-end | center | baseline | stretch;）',
ALIGN_CONTENT  VARCHAR (50) COMMENT '项目多向对齐方式（flex-start | flex-end | center | space-between | space-around | stretch;）',
EXT_ATTRIBUTS  VARCHAR (500) COMMENT '扩展属性',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (LAYOUT_ID)
)
 COMMENT = '开发中心-分析布局定义表';

-- 分析布局项目定义表
CREATE TABLE DEV_ANALYSIS_LAYOUT_ITEM_DEF(
ITEM_ID  VARCHAR (32) NOT NULL  COMMENT '项目编号',
LAYOUT_ID  VARCHAR (32) NOT NULL  COMMENT '布局编号',
ITEM_ORDER  DECIMAL(5) COMMENT '项目排序',
WIDTH  VARCHAR (20) COMMENT '项目宽度',
HEIGHT  VARCHAR (20) COMMENT '项目高度',
FLEX_GROW  VARCHAR (50) COMMENT '项目的放大比例（默认为0）',
FLEX_SHRINK  VARCHAR (50) COMMENT '项目的缩小比例(默认为1)',
FLEX_BASIS  VARCHAR (50) COMMENT '项目占据的主轴空间（flex-start | flex-end | center | space-between | space-around | stretch;）',
ALIGN_SELF  VARCHAR (50) COMMENT '项目对齐方式(auto | flex-start | flex-end | center | baseline | stretch;)',
EXT_ATTRIBUTS  VARCHAR (500) COMMENT '扩展属性',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (ITEM_ID)
)
 COMMENT = '开发中心-分析布局项目定义表';

-- 分析信息表
CREATE TABLE DEV_ANALYSIS_INFO(
ANALYSIS_ID  VARCHAR (32) NOT NULL  COMMENT '分析编号',
ANALYSIS_TYPE  VARCHAR (32) NOT NULL  COMMENT '分析类型（0-单表分析，1-组合分析，2-仪表分析……）',
ANALYSIS_NAME  VARCHAR (50) COMMENT '分析名称',
LAYOUT_ID  VARCHAR (32) COMMENT '布局编号',
ITEM_COUNT  DECIMAL(5) COMMENT '容纳数量',
WIDTH  VARCHAR (20) COMMENT '容器宽度',
HEIGHT  VARCHAR (20) COMMENT '容器高度',
TOP  VARCHAR (20) COMMENT '上边距',
LEFT  VARCHAR (20) COMMENT '左边距',
FLEX_WRAP  VARCHAR (50) COMMENT '项目换行方式（nowrap | wrap | wrap-reverse;）',
JUSTIFY_CONTENT  VARCHAR (50) COMMENT '项目水平对齐方式（flex-start | flex-end | center | space-between | space-around;）',
ALIGN_ITEMS  VARCHAR (50) COMMENT '项目垂直对齐方式（flex-start | flex-end | center | baseline | stretch;）',
ALIGN_CONTENT  VARCHAR (50) COMMENT '项目多向对齐方式（flex-start | flex-end | center | space-between | space-around | stretch;）',
EXT_ATTRIBUTS  VARCHAR (500) COMMENT '扩展属性',
STATUS  VARCHAR (1) COMMENT '状态（0-创建，1-存草稿，2-分享，3-发布）',
INDEX_PATH  varchar(32) COMMENT '索引路径',
ICONS  varchar(300) COMMENT '图标',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (ANALYSIS_ID)
)
 COMMENT = '开发中心-分析信息表';

-- 分析项目信息表
CREATE TABLE DEV_ANALYSIS_ITEM_INFO(
ANALYSIS_ITEM_ID  VARCHAR (32) NOT NULL  COMMENT '分析项目编号',
ANALYSIS_ID  VARCHAR (32) NOT NULL  COMMENT '分析编号',
REPORT_ID  VARCHAR (32) NOT NULL  COMMENT '报表编号',
ITEM_ID  VARCHAR (32) COMMENT '项目编号',
LAYOUT_ID  VARCHAR (32) COMMENT '布局编号',
ITEM_ORDER  DECIMAL(5) COMMENT '项目排序',
WIDTH  VARCHAR (20) COMMENT '宽度',
HEIGHT  VARCHAR (20) COMMENT '高度',
TOP_PAD  VARCHAR (20) COMMENT '上边距',
LEFT_PAD  VARCHAR (20) COMMENT '左边距',
FLEX_GROW  VARCHAR (50) COMMENT '项目的放大比例（默认为0）',
FLEX_SHRINK  VARCHAR (50) COMMENT '项目的缩小比例(默认为1)',
FLEX_BASIS  VARCHAR (50) COMMENT '项目占据的主轴空间（flex-start | flex-end | center | space-between | space-around | stretch;）',
ALIGN_SELF  VARCHAR (50) COMMENT '项目对齐方式(auto | flex-start | flex-end | center | baseline | stretch;)',
EXT_ATTRIBUTS  VARCHAR (500) COMMENT '扩展属性',
CRT_USER_CODE  VARCHAR (32) COMMENT '创建人',
CRT_ORG_CODE  VARCHAR (32) COMMENT '创建机构',
CRT_DATE  TIMESTAMP COMMENT '创建日期',
UPD_USER_CODE  VARCHAR (32) COMMENT '修改人',
UPD_ORG_CODE  VARCHAR (32) COMMENT '修改机构',
UPD_DATE  TIMESTAMP COMMENT '修改日期',
 PRIMARY KEY (ANALYSIS_ITEM_ID)
)
 COMMENT = '开发中心-分析项目信息表';


