-- 建表脚本-Oracle
-- 索引目录表
CREATE TABLE DEV_INDEX_PATH(
  PATH_ID  varchar(32) NOT NULL,
  PATH_NAME  varchar(200),
  PARENT_ID  varchar(32),
  PATH_TEXT  varchar(500),
  PATH_MODULE  varchar(500),
  PATH_LEVEL  DECIMAL(5),
  PATH_ICONS  varchar(300),
  PATH_ORDER  DECIMAL(5),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_INDEX_PATH PRIMARY KEY (PATH_ID)
);
 COMMENT ON TABLE DEV_INDEX_PATH IS '开发中心-索引目录表';
 COMMENT ON COLUMN DEV_INDEX_PATH.PATH_ID IS  '路径编号';
COMMENT ON COLUMN DEV_INDEX_PATH.PATH_NAME IS  '路径名称';
COMMENT ON COLUMN DEV_INDEX_PATH.PARENT_ID IS  '上级路径';
COMMENT ON COLUMN DEV_INDEX_PATH.PATH_TEXT IS  '全路径';
COMMENT ON COLUMN DEV_INDEX_PATH.PATH_MODULE IS  '功能模块';
COMMENT ON COLUMN DEV_INDEX_PATH.PATH_LEVEL IS  '路径层级';
COMMENT ON COLUMN DEV_INDEX_PATH.PATH_ICONS IS  '图标';
COMMENT ON COLUMN DEV_INDEX_PATH.PATH_ORDER IS  '路径排序';
COMMENT ON COLUMN DEV_INDEX_PATH.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_INDEX_PATH.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_INDEX_PATH.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_INDEX_PATH.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_INDEX_PATH.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_INDEX_PATH.UPD_DATE IS  '修改日期';

-- 数据源表
CREATE TABLE DEV_DATA_SOURCE(
  SOURCE_ID  varchar(32) NOT NULL,
  SOURCE_NAME  varchar(200),
  SOURCE_DESC  varchar(500),
  SOURCE_TYPE  varchar(2),
  DRIVE_TYPE  varchar(50),
  DRIVE_CLASS  varchar(100),
  CONN_URL  varchar(500),
  DB_NAME  varchar(255),
  USER_NAME  varchar(50),
  PASSWORD  varchar(100),
  SRC_CHARACTER  varchar(100),
  GOAL_CHARACTER  varchar(100),
  VERIFY_TYPE  varchar(1),
  MAX_CONN  DECIMAL(11),
  CHECK_TYPE  varchar(1),
  SENTERNCE  varchar(300),
  TRAN_LEVEL  varchar(1),
  REF_ID  varchar(300),
  STATUS  varchar(1),
  INDEX_PATH  varchar(32),
  ICONS  varchar(300),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_DATA_SOURCE PRIMARY KEY (SOURCE_ID)
);
 COMMENT ON TABLE DEV_DATA_SOURCE IS '开发中心-数据源表';
 COMMENT ON COLUMN DEV_DATA_SOURCE.SOURCE_ID IS  '数据源编号';
COMMENT ON COLUMN DEV_DATA_SOURCE.SOURCE_NAME IS  '数据源名称';
COMMENT ON COLUMN DEV_DATA_SOURCE.SOURCE_DESC IS  '数据源描述';
COMMENT ON COLUMN DEV_DATA_SOURCE.SOURCE_TYPE IS  '数据源类型（0-关系型数据源，1-文件数据源，2-服务型数据源）';
COMMENT ON COLUMN DEV_DATA_SOURCE.DRIVE_TYPE IS  '驱动程序类型（mysql、Db2……，excel、txt）';
COMMENT ON COLUMN DEV_DATA_SOURCE.DRIVE_CLASS IS  '驱动程序类';
COMMENT ON COLUMN DEV_DATA_SOURCE.CONN_URL IS  '连接URL';
COMMENT ON COLUMN DEV_DATA_SOURCE.DB_NAME IS  '数据库名';
COMMENT ON COLUMN DEV_DATA_SOURCE.USER_NAME IS  '用户名';
COMMENT ON COLUMN DEV_DATA_SOURCE.PASSWORD IS  '密码';
COMMENT ON COLUMN DEV_DATA_SOURCE.SRC_CHARACTER IS  '数据源字符集';
COMMENT ON COLUMN DEV_DATA_SOURCE.GOAL_CHARACTER IS  '数据源目标字符集';
COMMENT ON COLUMN DEV_DATA_SOURCE.VERIFY_TYPE IS  '验证类型（0-静态1-动态）';
COMMENT ON COLUMN DEV_DATA_SOURCE.MAX_CONN IS  '最大连接数';
COMMENT ON COLUMN DEV_DATA_SOURCE.CHECK_TYPE IS  '检验类型';
COMMENT ON COLUMN DEV_DATA_SOURCE.SENTERNCE IS  '检验语句';
COMMENT ON COLUMN DEV_DATA_SOURCE.TRAN_LEVEL IS  '事务隔离级别';
COMMENT ON COLUMN DEV_DATA_SOURCE.REF_ID IS  '引用标识符';
COMMENT ON COLUMN DEV_DATA_SOURCE.STATUS IS  '状态（0-创建，1-存草稿，2-分享，3-发布）';
COMMENT ON COLUMN DEV_DATA_SOURCE.INDEX_PATH IS  '索引路径';
COMMENT ON COLUMN DEV_DATA_SOURCE.ICONS IS  '图标';
COMMENT ON COLUMN DEV_DATA_SOURCE.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_DATA_SOURCE.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_DATA_SOURCE.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_DATA_SOURCE.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_DATA_SOURCE.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_DATA_SOURCE.UPD_DATE IS  '修改日期';

-- 数据表表
CREATE TABLE DEV_DATA_TABLE(
  TABLE_ID  VARCHAR2 (32) NOT NULL,
  SOURCE_ID  varchar(32) NOT NULL,
  SOURCE_NAME  varchar(255) NOT NULL,
  TABLE_NAME  VARCHAR2 (255),
  TABLE_DESC  VARCHAR2 (255),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_DATA_TABLE PRIMARY KEY (TABLE_ID)
);
 COMMENT ON TABLE DEV_DATA_TABLE IS '开发中心-数据表表';
 COMMENT ON COLUMN DEV_DATA_TABLE.TABLE_ID IS  '表编号';
COMMENT ON COLUMN DEV_DATA_TABLE.SOURCE_ID IS  '数据源编号';
COMMENT ON COLUMN DEV_DATA_TABLE.SOURCE_NAME IS  '数据源名称';
COMMENT ON COLUMN DEV_DATA_TABLE.TABLE_NAME IS  '表名称';
COMMENT ON COLUMN DEV_DATA_TABLE.TABLE_DESC IS  '表描述';
COMMENT ON COLUMN DEV_DATA_TABLE.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_DATA_TABLE.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_DATA_TABLE.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_DATA_TABLE.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_DATA_TABLE.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_DATA_TABLE.UPD_DATE IS  '修改日期';

-- 数据源列表
CREATE TABLE DEV_DATA_COLUMN(
  COLUMN_ID  VARCHAR2 (32) NOT NULL,
  TABLE_ID  VARCHAR2 (32) NOT NULL,
  SOURCE_ID  varchar(32) NOT NULL,
  TABLE_NAME  VARCHAR2 (100),
  TABLE_DESC  VARCHAR2 (255),
  COLUMN_NAME  VARCHAR2 (100),
  COLUMN_DESC  VARCHAR2 (255),
  COLUMN_TYPE  VARCHAR2 (50),
  COLUMN_ORDER  DECIMAL(5),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_DATA_COLUMN PRIMARY KEY (COLUMN_ID)
);
 COMMENT ON TABLE DEV_DATA_COLUMN IS '开发中心-数据列表';
 COMMENT ON COLUMN DEV_DATA_COLUMN.COLUMN_ID IS  '列编号';
COMMENT ON COLUMN DEV_DATA_COLUMN.TABLE_ID IS  '表编号';
COMMENT ON COLUMN DEV_DATA_COLUMN.SOURCE_ID IS  '数据源编号';
COMMENT ON COLUMN DEV_DATA_COLUMN.TABLE_NAME IS  '表名称';
COMMENT ON COLUMN DEV_DATA_COLUMN.TABLE_DESC IS  '表描述';
COMMENT ON COLUMN DEV_DATA_COLUMN.COLUMN_NAME IS  '列名称';
COMMENT ON COLUMN DEV_DATA_COLUMN.COLUMN_DESC IS  '列描述';
COMMENT ON COLUMN DEV_DATA_COLUMN.COLUMN_TYPE IS  '列类型';
COMMENT ON COLUMN DEV_DATA_COLUMN.COLUMN_ORDER IS  '字段顺序';
COMMENT ON COLUMN DEV_DATA_COLUMN.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_DATA_COLUMN.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_DATA_COLUMN.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_DATA_COLUMN.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_DATA_COLUMN.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_DATA_COLUMN.UPD_DATE IS  '修改日期';

-- 参数信息表
CREATE TABLE DEV_PARAM_PARAMETER(
  PARAMETER_ID  VARCHAR2 (32) NOT NULL,
  PARAMETER_NAME  VARCHAR2 (200) NOT NULL,
  PARAMETER_DESC  VARCHAR2 (200),
  PARAMETER_TYPE  VARCHAR2 (2),
  DATA_TYPE  VARCHAR2 (2),
  COMPONENT_TYPE  VARCHAR2 (3),
  COMPONENT_WIDTH  DECIMAL(5),
  COMPONENT_HEIGHT  DECIMAL(5),
  CONTENT_WIDTH  DECIMAL(5),
  CONTENT_HEIGHT  DECIMAL(5),
  DEFAULT_VALUE  VARCHAR2 (300),
  DEFAULT_EXPR  VARCHAR2 (300),
  SELECTED_VALUE  VARCHAR2 (200),
  SELECTED_EXPR  VARCHAR2 (500),
  SELECTED_VAL_TYPE  VARCHAR2 (2),
  LINK_TABLE  VARCHAR2 (200),
  STATUS  varchar(1),
  INDEX_PATH  varchar(32),
  ICONS  varchar(300),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_PARAM_PARAMETER PRIMARY KEY (PARAMETER_ID)
);
 COMMENT ON TABLE DEV_PARAM_PARAMETER IS '开发中心-参数信息表';
 COMMENT ON COLUMN DEV_PARAM_PARAMETER.PARAMETER_ID IS  '参数编号';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.PARAMETER_NAME IS  '参数名称';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.PARAMETER_DESC IS  '参数描述';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.PARAMETER_TYPE IS  '参数类型(0-全局参数 1-私有参数)';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.DATA_TYPE IS  '数据类型，0字符串，1整形 ，2浮点型，3日期，4时间，5日期时间';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.COMPONENT_TYPE IS  '控件类型：0文本框，1勾选框，2下拉框，3树形对话框，4日期时间控件';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.COMPONENT_WIDTH IS  '控件宽度';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.COMPONENT_HEIGHT IS  '控件高度';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.CONTENT_WIDTH IS  '控件下拉框宽度';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.CONTENT_HEIGHT IS  '控件下拉框高度';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.DEFAULT_VALUE IS  '默认值';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.DEFAULT_EXPR IS  '默认值表达式';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.SELECTED_VALUE IS  '备选值';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.SELECTED_EXPR IS  '备选值表达式';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.SELECTED_VAL_TYPE IS  '备选值类型';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.LINK_TABLE IS  '参数所属表';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.STATUS IS  '状态（0-创建，1-存草稿，2-分享，3-发布）';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.INDEX_PATH IS  '索引路径';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.ICONS IS  '图标';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_PARAM_PARAMETER.UPD_DATE IS  '修改日期';

-- 查询主信息表
CREATE TABLE DEV_INQUIRY_MAIN(
  INQUIRY_ID  VARCHAR2 (32) NOT NULL,
  INQUIRY_NAME  VARCHAR2 (200) NOT NULL,
  INQUIRY_TYPE  VARCHAR2 (2),
  SOURCE_ID  varchar(32),
  ORIG_SQL  VARCHAR2 (10000),
  EXECUTE_SQL  VARCHAR2 (10000),
  STATUS  VARCHAR2 (1),
  INDEX_PATH  varchar(32),
  ICONS  varchar(300),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_INQUIRY_MAIN PRIMARY KEY (INQUIRY_ID)
);
 COMMENT ON TABLE DEV_INQUIRY_MAIN IS '开发中心-查询主信息表';
 COMMENT ON COLUMN DEV_INQUIRY_MAIN.INQUIRY_ID IS  '查询编号';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.INQUIRY_NAME IS  '查询名称';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.INQUIRY_TYPE IS  '查询类型（00-sql，01-可视化，10-excel，11-txt，20-服务）';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.SOURCE_ID IS  '数据源编号';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.ORIG_SQL IS  '原始SQL(文件名、服务名)';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.EXECUTE_SQL IS  '执行SQL（文件路径、服务信息）';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.STATUS IS  '状态（0-创建，1-存草稿，2-分享，3-发布）';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.INDEX_PATH IS  '索引路径';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.ICONS IS  '图标';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_INQUIRY_MAIN.UPD_DATE IS  '修改日期';

-- 查询表信息表
CREATE TABLE DEV_INQUIRY_TABLE(
  TABLE_ID  VARCHAR2 (32) NOT NULL,
  INQUIRY_ID  VARCHAR2 (32) NOT NULL,
  TABLE_NAME  VARCHAR2 (100) NOT NULL,
  TABLE_ALIAS  VARCHAR2 (100),
  TABLE_DESC  VARCHAR2 (200),
  TABLE_ORDER  DECIMAL(5),
  TABLE_TYPE  VARCHAR2 (20),
  TABLE_SCHEMA  VARCHAR2 (50),
  REL_TABLE  VARCHAR2 (100),
  REL_TYPE  VARCHAR2 (5),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_INQUIRY_TABLE PRIMARY KEY (TABLE_ID)
);
 COMMENT ON TABLE DEV_INQUIRY_TABLE IS '开发中心-查询表信息表';
 COMMENT ON COLUMN DEV_INQUIRY_TABLE.TABLE_ID IS  '查询表编号';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.INQUIRY_ID IS  '查询编号';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.TABLE_NAME IS  '表名称';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.TABLE_ALIAS IS  '表别名';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.TABLE_DESC IS  '表描述';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.TABLE_ORDER IS  '表顺序';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.TABLE_TYPE IS  '表类型';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.TABLE_SCHEMA IS  '所属表别名';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.REL_TABLE IS  '关联表名称';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.REL_TYPE IS  '关联方式（0-内关联，1-左关联，2-右关联）';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_INQUIRY_TABLE.UPD_DATE IS  '修改日期';

-- 查询输出列信息表
CREATE TABLE DEV_INQUIRY_COLUMN(
  COLUMN_ID  VARCHAR2 (32) NOT NULL,
  INQUIRY_ID  VARCHAR2 (32) NOT NULL,
  COLUMN_NAME  VARCHAR2 (100),
  COLUMN_ALIAS  VARCHAR2 (100),
  COLUMN_DESC  VARCHAR2 (200),
  COLUMN_ORDER  DECIMAL(5),
  COLUMN_TYPE  VARCHAR2 (20),
  COLUMN_HIDDEN  VARCHAR2 (2),
  TABLE_ALIAS  VARCHAR2 (1),
  IS_NUMBER  VARCHAR2 (1),
  IS_AGGREGATE  VARCHAR2 (1),
  AGGREGATE_TYPE  VARCHAR2 (1),
  AGGREGATE  VARCHAR2 (100),
  IS_GROUP_COLUMN  VARCHAR2 (1),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_INQUIRY_COLUMN PRIMARY KEY (COLUMN_ID)
);
 COMMENT ON TABLE DEV_INQUIRY_COLUMN IS '开发中心-查询输出列信息表';
 COMMENT ON COLUMN DEV_INQUIRY_COLUMN.COLUMN_ID IS  '列编号';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.INQUIRY_ID IS  '查询编号';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.COLUMN_NAME IS  '字段名称';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.COLUMN_ALIAS IS  '字段别名';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.COLUMN_DESC IS  '字段描述';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.COLUMN_ORDER IS  '字段顺序';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.COLUMN_TYPE IS  '字段类型';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.COLUMN_HIDDEN IS  '字段隐藏（1-隐藏，0-显示）';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.TABLE_ALIAS IS  '所属表别名';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.IS_NUMBER IS  '是否数字类型（1-是，0-否）';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.IS_AGGREGATE IS  '是否聚合函数0否1是';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.AGGREGATE_TYPE IS  '聚合函数类型0一般1特殊';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.AGGREGATE IS  '聚合函数';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.IS_GROUP_COLUMN IS  '是否分组字段（0-否，1-是）';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_INQUIRY_COLUMN.UPD_DATE IS  '修改日期';

-- 查询条件信息表
CREATE TABLE DEV_INQUIRY_CONDITION(
  COND_ID  VARCHAR2 (32) NOT NULL,
  INQUIRY_ID  VARCHAR2 (32) NOT NULL,
  TABLE_ID  VARCHAR2 (32),
  COND_TYPE  VARCHAR2 (2),
  COND_PREFIX  VARCHAR2 (20),
  COND_COLUMN  VARCHAR2 (100),
  COND_SYMBOL  VARCHAR2 (20),
  COND_VALUE  VARCHAR2 (200),
  COND_POSTFIX  VARCHAR2 (20),
  COND_ORDER  DECIMAL(5),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_INQUIRY_CONDITION PRIMARY KEY (COND_ID)
);
 COMMENT ON TABLE DEV_INQUIRY_CONDITION IS '开发中心-查询条件信息表';
 COMMENT ON COLUMN DEV_INQUIRY_CONDITION.COND_ID IS  '条件编号';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.INQUIRY_ID IS  '查询编号';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.TABLE_ID IS  '表编号';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.COND_TYPE IS  '条件类型（0-常量筛选条件，1-关联条件，2-参数条件，3-权限过滤）';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.COND_PREFIX IS  '表达式前缀';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.COND_COLUMN IS  '条件表达式';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.COND_SYMBOL IS  '条件表达式运算符';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.COND_VALUE IS  '条件表达式值';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.COND_POSTFIX IS  '表达式后缀';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.COND_ORDER IS  '条件排序';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_INQUIRY_CONDITION.UPD_DATE IS  '修改日期';

-- 图表定义主表
CREATE TABLE DEV_REPORT_DEFINE(
  CHARTS_ID  VARCHAR2 (32) NOT NULL,
  CHARTS_TYPE  VARCHAR2 (50) NOT NULL,
  CHARTS_NAME  VARCHAR2 (200),
  CHARTS_CATEGORY  VARCHAR2 (32),
  ICONS  VARCHAR2 (300),
  CHARTS_DIM_MIN  DECIMAL(5),
  CHARTS_DIM_MAX  DECIMAL(5),
  CHARTS_MEA_MIN  DECIMAL(5),
  CHARTS_MEA_MAX  DECIMAL(5),
  CHARTS_DATE_NUM  DECIMAL(5),
  CHARTS_PLACE_NUM  DECIMAL(5),
  COMPONENT_NAME  VARCHAR2 (100),
  CHART_ORDER  INT,
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_DEFINE PRIMARY KEY (CHARTS_ID)
);
 COMMENT ON TABLE DEV_REPORT_DEFINE IS '开发中心-图表定义主表';
 COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_ID IS  '图表编号';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_TYPE IS  '图表类型';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_NAME IS  '图表名称';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_CATEGORY IS  '图表分类';
COMMENT ON COLUMN DEV_REPORT_DEFINE.ICONS IS  '图标';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_DIM_MIN IS  '维度最小数';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_DIM_MAX IS  '维度最大数';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_MEA_MIN IS  '度量最小数';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_MEA_MAX IS  '度量最大数';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_DATE_NUM IS  '日期数量';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHARTS_PLACE_NUM IS  '地理数量';
COMMENT ON COLUMN DEV_REPORT_DEFINE.COMPONENT_NAME IS  '组件名称';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CHART_ORDER IS  '排序';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_DEFINE.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_DEFINE.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_DEFINE.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_DEFINE.UPD_DATE IS  '修改日期';

-- 图表定义_国际化表
CREATE TABLE DEV_REPORT_DEFINE_I18N(
  I18N_ID  VARCHAR2 (32) NOT NULL,
  CHARTS_ID  VARCHAR2 (32) NOT NULL,
  LANGUAGE  VARCHAR2 (10),
  COUNTRY  VARCHAR2 (10),
  CHARTS_NAME  VARCHAR2 (200),
  CHARTS_COMMENT  VARCHAR2 (500),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_DEFINE_I18N PRIMARY KEY (I18N_ID)
);
 COMMENT ON TABLE DEV_REPORT_DEFINE_I18N IS '开发中心-图表定义国际化表';
 COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.I18N_ID IS  '国际化编号';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.CHARTS_ID IS  '图表编号';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.LANGUAGE IS  '语言';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.COUNTRY IS  '国家';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.CHARTS_NAME IS  '图表名称';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.CHARTS_COMMENT IS  '图表说明';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_DEFINE_I18N.UPD_DATE IS  '修改日期';

-- 图表定义属性表
CREATE TABLE DEV_REPORT_ATTR_DEF(
  CHARTS_ATTR_ID  VARCHAR2 (32) NOT NULL,
  CHARTS_ID  VARCHAR2 (32),
  PARENT_ATTR_ID  VARCHAR2 (32),
  CHARTS_ATTR_TYPE  VARCHAR2 (20),
  CHARTS_ATTR_NAME  VARCHAR2 (100),
  CHARTS_ATTR_VALUE  VARCHAR2 (200),
  CHARTS_ATTR_DESC  VARCHAR2 (200),
  CHARTS_ATTR_ORDER  DECIMAL(5),
  COMPONENT_TYPE  VARCHAR2 (50),
  COMPONENT_OPTIONS  VARCHAR2 (500),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_ATTR_DEF PRIMARY KEY (CHARTS_ATTR_ID)
);
 COMMENT ON TABLE DEV_REPORT_ATTR_DEF IS '开发中心-图表定义属性表';
 COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CHARTS_ATTR_ID IS  '图表属性编号';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CHARTS_ID IS  '图表编号';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.PARENT_ATTR_ID IS  '上级属性ID';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CHARTS_ATTR_TYPE IS  '图表属性类型(String,Object,ARRAY)';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CHARTS_ATTR_NAME IS  '图表属性名称';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CHARTS_ATTR_VALUE IS  '图表属性值';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CHARTS_ATTR_DESC IS  '图表属性描述';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CHARTS_ATTR_ORDER IS  '属性排序';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.COMPONENT_TYPE IS  '组件类型';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.COMPONENT_OPTIONS IS  '可选值';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_ATTR_DEF.UPD_DATE IS  '修改日期';

-- 图表定义属性_国际化表
CREATE TABLE DEV_REPORT_ATTR_I18N(
  I18N_ID  VARCHAR2 (32) NOT NULL,
  CHARTS_ATTR_ID  VARCHAR2 (32) NOT NULL,
  LANGUAGE  VARCHAR2 (10),
  COUNTRY  VARCHAR2 (10),
  CHARTS_ATTR_DESC  VARCHAR2 (200),
  COMPONENT_OPTIONS  VARCHAR2 (500),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_ATTR_I18N PRIMARY KEY (I18N_ID)
);
 COMMENT ON TABLE DEV_REPORT_ATTR_I18N IS '开发中心-图表定义属性国际化表';
 COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.I18N_ID IS  '图表属性编号';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.CHARTS_ATTR_ID IS  '图表属性编号';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.LANGUAGE IS  '语言';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.COUNTRY IS  '国家';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.CHARTS_ATTR_DESC IS  '图表属性描述';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.COMPONENT_OPTIONS IS  '可选值';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_ATTR_I18N.UPD_DATE IS  '修改日期';

-- 图表定义绑定表
CREATE TABLE DEV_REPORT_BIND_DEF(
  CHARTS_BIND_ID  VARCHAR2 (32) NOT NULL,
  CHARTS_ID  VARCHAR2 (32),
  BIND_NAME  VARCHAR2 (100),
  BIND_TYPE  VARCHAR2 (20),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_BIND_DEF PRIMARY KEY (CHARTS_BIND_ID)
);
 COMMENT ON TABLE DEV_REPORT_BIND_DEF IS '开发中心-图表定义绑定表';
 COMMENT ON COLUMN DEV_REPORT_BIND_DEF.CHARTS_BIND_ID IS  '绑定编号';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.CHARTS_ID IS  '图表编号';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.BIND_NAME IS  '绑定名称';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.BIND_TYPE IS  '绑定数据类型（0-任意，1-数字）';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_BIND_DEF.UPD_DATE IS  '修改日期';

-- 图表信息主表
CREATE TABLE DEV_REPORT_INFO(
  REPORT_ID  VARCHAR2 (32) NOT NULL,
  REPORT_NAME  VARCHAR2 (200),
  REPORT_DESC  VARCHAR2 (200),
  CHARTS_ID  VARCHAR2 (32),
  CHARTS_TYPE  VARCHAR2 (2),
  INQUIRY_ID  VARCHAR2 (32),
  REPORT  text,
  CHARTS_DIM_MIN  DECIMAL(5),
  CHARTS_DIM_MAX  DECIMAL(5),
  CHARTS_MEA_MIN  DECIMAL(5),
  CHARTS_MEA_MAX  DECIMAL(5),
  STATUS  VARCHAR2 (1),
  INDEX_PATH  varchar(32),
  ICONS  varchar(300),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_INFO PRIMARY KEY (REPORT_ID)
);
 COMMENT ON TABLE DEV_REPORT_INFO IS '开发中心-图表信息主表';
 COMMENT ON COLUMN DEV_REPORT_INFO.REPORT_ID IS  '报表编号';
COMMENT ON COLUMN DEV_REPORT_INFO.REPORT_NAME IS  '报表名称';
COMMENT ON COLUMN DEV_REPORT_INFO.REPORT_DESC IS  '报表描述';
COMMENT ON COLUMN DEV_REPORT_INFO.CHARTS_ID IS  '图表编号';
COMMENT ON COLUMN DEV_REPORT_INFO.CHARTS_TYPE IS  '图表类型';
COMMENT ON COLUMN DEV_REPORT_INFO.INQUIRY_ID IS  '查询编号';
COMMENT ON COLUMN DEV_REPORT_INFO.REPORT IS  '报表内容（固定报表）';
COMMENT ON COLUMN DEV_REPORT_INFO.CHARTS_DIM_MIN IS  '维度最小数';
COMMENT ON COLUMN DEV_REPORT_INFO.CHARTS_DIM_MAX IS  '维度最大数';
COMMENT ON COLUMN DEV_REPORT_INFO.CHARTS_MEA_MIN IS  '度量最小数';
COMMENT ON COLUMN DEV_REPORT_INFO.CHARTS_MEA_MAX IS  '度量最大数';
COMMENT ON COLUMN DEV_REPORT_INFO.STATUS IS  '状态（0-创建，1-存草稿，2-分享，3-发布）';
COMMENT ON COLUMN DEV_REPORT_INFO.INDEX_PATH IS  '索引路径';
COMMENT ON COLUMN DEV_REPORT_INFO.ICONS IS  '图标';
COMMENT ON COLUMN DEV_REPORT_INFO.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_INFO.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_INFO.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_INFO.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_INFO.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_INFO.UPD_DATE IS  '修改日期';

-- 图表信息属性表
CREATE TABLE DEV_REPORT_ATTR_INFO(
  REPORT_ATTR_ID  VARCHAR2 (32) NOT NULL,
  REPORT_ID  VARCHAR2 (32) NOT NULL,
  CHARTS_ATTR_ID  VARCHAR2 (32),
  CHARTS_ID  VARCHAR2 (32),
  PARENT_ATTR_ID  VARCHAR2 (32),
  CHARTS_ATTR_TYPE  VARCHAR2 (20),
  CHARTS_ATTR_NAME  VARCHAR2 (100),
  CHARTS_ATTR_VALUE  VARCHAR2 (200),
  CHARTS_ATTR_DESC  VARCHAR2 (200),
  COMPONENT_TYPE  VARCHAR2 (50),
  COMPONENT_OPTIONS  VARCHAR2 (500),
  CHARTS_ATTR_ORDER  DECIMAL(5),
  IS_CUSTOM  VARCHAR2 (1),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_ATTR_INFO PRIMARY KEY (REPORT_ATTR_ID)
);
 COMMENT ON TABLE DEV_REPORT_ATTR_INFO IS '开发中心-图表信息属性表';
 COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.REPORT_ATTR_ID IS  '报表属性编号';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.REPORT_ID IS  '报表编号';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CHARTS_ATTR_ID IS  '图表属性编号';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CHARTS_ID IS  '图表编号';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.PARENT_ATTR_ID IS  '上级属性ID';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CHARTS_ATTR_TYPE IS  '图表属性类型(String,Object,ARRAY)';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CHARTS_ATTR_NAME IS  '图表属性名称';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CHARTS_ATTR_VALUE IS  '图表属性值';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CHARTS_ATTR_DESC IS  '图表属性描述';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.COMPONENT_TYPE IS  '组件类型';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.COMPONENT_OPTIONS IS  '可选值';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CHARTS_ATTR_ORDER IS  '属性排序';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.IS_CUSTOM IS  '是否自定义';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_ATTR_INFO.UPD_DATE IS  '修改日期';

-- 图表信息绑定表
CREATE TABLE DEV_REPORT_BIND_INFO(
  REPORT_BIND_ID  VARCHAR2 (32) NOT NULL,
  REPORT_ID  VARCHAR2 (32) NOT NULL,
  CHARTS_BIND_ID  VARCHAR2 (32) NOT NULL,
  CHARTS_ID  VARCHAR2 (32),
  BIND_NAME  VARCHAR2 (100),
  BIND_TYPE  VARCHAR2 (20),
  BIND_VALUE  VARCHAR2 (200),
  BIND_DESC  VARCHAR2 (200),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_BIND_INFO PRIMARY KEY (REPORT_BIND_ID)
);
 COMMENT ON TABLE DEV_REPORT_BIND_INFO IS '开发中心-图表定义绑定表';
 COMMENT ON COLUMN DEV_REPORT_BIND_INFO.REPORT_BIND_ID IS  '报表绑定编号';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.REPORT_ID IS  '报表编号';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.CHARTS_BIND_ID IS  '图表绑定编号';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.CHARTS_ID IS  '图表编号';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.BIND_NAME IS  '绑定名称';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.BIND_TYPE IS  '绑定数据类型（0-任意，1-数字）';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.BIND_VALUE IS  '绑定值';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.BIND_DESC IS  '绑定值描述';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_BIND_INFO.UPD_DATE IS  '修改日期';

-- 图表输出列信息表
CREATE TABLE DEV_REPORT_COLUMN(
  REPORT_COLUMN_ID  VARCHAR2 (32) NOT NULL,
  REPORT_ID  VARCHAR2 (32) NOT NULL,
  INQUIRY_ID  VARCHAR2 (32) NOT NULL,
  COLUMN_NAME  VARCHAR2 (100),
  COLUMN_ALIAS  VARCHAR2 (100),
  COLUMN_DESC  VARCHAR2 (200),
  COLUMN_ORDER  DECIMAL(5),
  COLUMN_TYPE  VARCHAR2 (20),
  COLUMN_BIND  VARCHAR2 (50),
  IS_NUMBER  VARCHAR2 (1),
  IS_AGGREGATE  VARCHAR2 (1),
  AGGREGATE_TYPE  VARCHAR2 (1),
  AGGREGATE  VARCHAR2 (100),
  IS_GROUP_COLUMN  VARCHAR2 (1),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_COLUMN PRIMARY KEY (REPORT_COLUMN_ID)
);
 COMMENT ON TABLE DEV_REPORT_COLUMN IS '开发中心-图表输出列信息表';
 COMMENT ON COLUMN DEV_REPORT_COLUMN.REPORT_COLUMN_ID IS  '报表列编号';
COMMENT ON COLUMN DEV_REPORT_COLUMN.REPORT_ID IS  '报表编号';
COMMENT ON COLUMN DEV_REPORT_COLUMN.INQUIRY_ID IS  '查询编号';
COMMENT ON COLUMN DEV_REPORT_COLUMN.COLUMN_NAME IS  '字段名称';
COMMENT ON COLUMN DEV_REPORT_COLUMN.COLUMN_ALIAS IS  '字段别名';
COMMENT ON COLUMN DEV_REPORT_COLUMN.COLUMN_DESC IS  '字段描述';
COMMENT ON COLUMN DEV_REPORT_COLUMN.COLUMN_ORDER IS  '字段顺序';
COMMENT ON COLUMN DEV_REPORT_COLUMN.COLUMN_TYPE IS  '字段类型';
COMMENT ON COLUMN DEV_REPORT_COLUMN.COLUMN_BIND IS  '字段绑定(row:行，col：列，value：值)';
COMMENT ON COLUMN DEV_REPORT_COLUMN.IS_NUMBER IS  '是否度量（1-是，0-否）';
COMMENT ON COLUMN DEV_REPORT_COLUMN.IS_AGGREGATE IS  '是否聚合函数0否1是';
COMMENT ON COLUMN DEV_REPORT_COLUMN.AGGREGATE_TYPE IS  '聚合函数类型0一般1特殊';
COMMENT ON COLUMN DEV_REPORT_COLUMN.AGGREGATE IS  '聚合函数';
COMMENT ON COLUMN DEV_REPORT_COLUMN.IS_GROUP_COLUMN IS  '是否分组字段（0-否，1-是）';
COMMENT ON COLUMN DEV_REPORT_COLUMN.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_COLUMN.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_COLUMN.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_COLUMN.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_COLUMN.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_COLUMN.UPD_DATE IS  '修改日期';

-- 图表信息参数表
CREATE TABLE DEV_REPORT_PARAM_INFO(
  REPORT_PARAM_ID  VARCHAR2 (32) NOT NULL,
  REPORT_ID  VARCHAR2 (32) NOT NULL,
  PARAMETER_ID  VARCHAR2 (32),
  COLUMN_ALIAS  VARCHAR2 (100),
  INQUIRY_ID  VARCHAR2 (32),
  COND_TYPE  VARCHAR2 (2),
  COND_PREFIX  VARCHAR2 (20),
  COND_COLUMN  VARCHAR2 (100),
  COND_SYMBOL  VARCHAR2 (20),
  COND_VALUE  VARCHAR2 (200),
  COND_POSTFIX  VARCHAR2 (20),
  COND_REQUIRED  VARCHAR2 (10),
  ICONS  varchar(300),
  COMPONENT_TYPE  VARCHAR2 (50),
  COMPONENT_OPTIONS  VARCHAR2 (500),
  CHARTS_ATTR_ORDER  DECIMAL(5),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_REPORT_PARAM_INFO PRIMARY KEY (REPORT_PARAM_ID)
);
 COMMENT ON TABLE DEV_REPORT_PARAM_INFO IS '开发中心-图表信息参数表';
 COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.REPORT_PARAM_ID IS  '报表参数编号';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.REPORT_ID IS  '报表编号';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.PARAMETER_ID IS  '参数编号';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COLUMN_ALIAS IS  '字段别名';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.INQUIRY_ID IS  '查询编号';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COND_TYPE IS  '条件类型（0-常量筛选条件，1-关联条件，2-参数条件，3-权限过滤）';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COND_PREFIX IS  '表达式前缀';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COND_COLUMN IS  '条件表达式';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COND_SYMBOL IS  '条件表达式运算符';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COND_VALUE IS  '条件表达式值';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COND_POSTFIX IS  '表达式后缀';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COND_REQUIRED IS  '是否必输';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.ICONS IS  '图标';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COMPONENT_TYPE IS  '组件类型';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.COMPONENT_OPTIONS IS  '可选值';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.CHARTS_ATTR_ORDER IS  '属性排序';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_REPORT_PARAM_INFO.UPD_DATE IS  '修改日期';

-- 分析布局定义表
CREATE TABLE DEV_ANALYSIS_LAYOUT_DEF(
  LAYOUT_ID  VARCHAR2 (32) NOT NULL,
  ITEM_COUNT  DECIMAL(5) NOT NULL,
  WIDTH  VARCHAR2 (20),
  HEIGHT  VARCHAR2 (20),
  FLEX_DIRECTION  VARCHAR2 (50),
  FLEX_WRAP  VARCHAR2 (50),
  JUSTIFY_CONTENT  VARCHAR2 (50),
  ALIGN_ITEMS  VARCHAR2 (50),
  ALIGN_CONTENT  VARCHAR2 (50),
  EXT_ATTRIBUTS  VARCHAR2 (500),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_ANALYSIS_LAYOUT_DEF PRIMARY KEY (LAYOUT_ID)
);
 COMMENT ON TABLE DEV_ANALYSIS_LAYOUT_DEF IS '开发中心-分析布局定义表';
 COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.LAYOUT_ID IS  '布局编号';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.ITEM_COUNT IS  '容纳数量';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.WIDTH IS  '容器宽度';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.HEIGHT IS  '容器高度';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.FLEX_DIRECTION IS  '项目的排列方向(row | row-reverse | column | column-reverse;)';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.FLEX_WRAP IS  '项目换行方式（nowrap | wrap | wrap-reverse;）';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.JUSTIFY_CONTENT IS  '项目水平对齐方式（flex-start | flex-end | center | space-between | space-around;）';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.ALIGN_ITEMS IS  '项目垂直对齐方式（flex-start | flex-end | center | baseline | stretch;）';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.ALIGN_CONTENT IS  '项目多向对齐方式（flex-start | flex-end | center | space-between | space-around | stretch;）';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.EXT_ATTRIBUTS IS  '扩展属性';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_DEF.UPD_DATE IS  '修改日期';

-- 分析布局项目定义表
CREATE TABLE DEV_ANALYSIS_LAYOUT_ITEM_DEF(
  ITEM_ID  VARCHAR2 (32) NOT NULL,
  LAYOUT_ID  VARCHAR2 (32) NOT NULL,
  ITEM_ORDER  DECIMAL(5),
  WIDTH  VARCHAR2 (20),
  HEIGHT  VARCHAR2 (20),
  FLEX_GROW  VARCHAR2 (50),
  FLEX_SHRINK  VARCHAR2 (50),
  FLEX_BASIS  VARCHAR2 (50),
  ALIGN_SELF  VARCHAR2 (50),
  EXT_ATTRIBUTS  VARCHAR2 (500),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_ANALYSIS_LAYOUT_ITEM_DEF PRIMARY KEY (ITEM_ID)
);
 COMMENT ON TABLE DEV_ANALYSIS_LAYOUT_ITEM_DEF IS '开发中心-分析布局项目定义表';
 COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.ITEM_ID IS  '项目编号';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.LAYOUT_ID IS  '布局编号';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.ITEM_ORDER IS  '项目排序';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.WIDTH IS  '项目宽度';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.HEIGHT IS  '项目高度';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.FLEX_GROW IS  '项目的放大比例（默认为0）';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.FLEX_SHRINK IS  '项目的缩小比例(默认为1)';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.FLEX_BASIS IS  '项目占据的主轴空间（flex-start | flex-end | center | space-between | space-around | stretch;）';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.ALIGN_SELF IS  '项目对齐方式(auto | flex-start | flex-end | center | baseline | stretch;)';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.EXT_ATTRIBUTS IS  '扩展属性';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_ANALYSIS_LAYOUT_ITEM_DEF.UPD_DATE IS  '修改日期';

-- 分析信息表
CREATE TABLE DEV_ANALYSIS_INFO(
  ANALYSIS_ID  VARCHAR2 (32) NOT NULL,
  ANALYSIS_TYPE  VARCHAR2 (32) NOT NULL,
  ANALYSIS_NAME  VARCHAR2 (50),
  LAYOUT_ID  VARCHAR2 (32),
  ITEM_COUNT  DECIMAL(5),
  WIDTH  VARCHAR2 (20),
  HEIGHT  VARCHAR2 (20),
  TOP  VARCHAR2 (20),
  LEFT  VARCHAR2 (20),
  FLEX_WRAP  VARCHAR2 (50),
  JUSTIFY_CONTENT  VARCHAR2 (50),
  ALIGN_ITEMS  VARCHAR2 (50),
  ALIGN_CONTENT  VARCHAR2 (50),
  EXT_ATTRIBUTS  VARCHAR2 (500),
  STATUS  VARCHAR2 (1),
  INDEX_PATH  varchar(32),
  ICONS  varchar(300),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_ANALYSIS_INFO PRIMARY KEY (ANALYSIS_ID)
);
 COMMENT ON TABLE DEV_ANALYSIS_INFO IS '开发中心-分析信息表';
 COMMENT ON COLUMN DEV_ANALYSIS_INFO.ANALYSIS_ID IS  '分析编号';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.ANALYSIS_TYPE IS  '分析类型（0-单表分析，1-组合分析，2-仪表分析……）';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.ANALYSIS_NAME IS  '分析名称';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.LAYOUT_ID IS  '布局编号';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.ITEM_COUNT IS  '容纳数量';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.WIDTH IS  '容器宽度';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.HEIGHT IS  '容器高度';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.TOP IS  '上边距';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.LEFT IS  '左边距';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.FLEX_WRAP IS  '项目换行方式（nowrap | wrap | wrap-reverse;）';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.JUSTIFY_CONTENT IS  '项目水平对齐方式（flex-start | flex-end | center | space-between | space-around;）';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.ALIGN_ITEMS IS  '项目垂直对齐方式（flex-start | flex-end | center | baseline | stretch;）';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.ALIGN_CONTENT IS  '项目多向对齐方式（flex-start | flex-end | center | space-between | space-around | stretch;）';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.EXT_ATTRIBUTS IS  '扩展属性';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.STATUS IS  '状态（0-创建，1-存草稿，2-分享，3-发布）';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.INDEX_PATH IS  '索引路径';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.ICONS IS  '图标';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_ANALYSIS_INFO.UPD_DATE IS  '修改日期';

-- 分析项目信息表
CREATE TABLE DEV_ANALYSIS_ITEM_INFO(
  ANALYSIS_ITEM_ID  VARCHAR2 (32) NOT NULL,
  ANALYSIS_ID  VARCHAR2 (32) NOT NULL,
  REPORT_ID  VARCHAR2 (32) NOT NULL,
  ITEM_ID  VARCHAR2 (32),
  LAYOUT_ID  VARCHAR2 (32),
  ITEM_ORDER  DECIMAL(5),
  WIDTH  VARCHAR2 (20),
  HEIGHT  VARCHAR2 (20),
  TOP_PAD  VARCHAR2 (20),
  LEFT_PAD  VARCHAR2 (20),
  FLEX_GROW  VARCHAR2 (50),
  FLEX_SHRINK  VARCHAR2 (50),
  FLEX_BASIS  VARCHAR2 (50),
  ALIGN_SELF  VARCHAR2 (50),
  EXT_ATTRIBUTS  VARCHAR2 (500),
  CRT_USER_CODE  VARCHAR2 (32),
  CRT_ORG_CODE  VARCHAR2 (32),
  CRT_DATE  DATE,
  UPD_USER_CODE  VARCHAR2 (32),
  UPD_ORG_CODE  VARCHAR2 (32),
  UPD_DATE  DATE,
CONSTRAINT DEV_ANALYSIS_ITEM_INFO PRIMARY KEY (ANALYSIS_ITEM_ID)
);
 COMMENT ON TABLE DEV_ANALYSIS_ITEM_INFO IS '开发中心-分析项目信息表';
 COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.ANALYSIS_ITEM_ID IS  '分析项目编号';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.ANALYSIS_ID IS  '分析编号';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.REPORT_ID IS  '报表编号';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.ITEM_ID IS  '项目编号';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.LAYOUT_ID IS  '布局编号';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.ITEM_ORDER IS  '项目排序';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.WIDTH IS  '宽度';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.HEIGHT IS  '高度';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.TOP_PAD IS  '上边距';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.LEFT_PAD IS  '左边距';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.FLEX_GROW IS  '项目的放大比例（默认为0）';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.FLEX_SHRINK IS  '项目的缩小比例(默认为1)';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.FLEX_BASIS IS  '项目占据的主轴空间（flex-start | flex-end | center | space-between | space-around | stretch;）';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.ALIGN_SELF IS  '项目对齐方式(auto | flex-start | flex-end | center | baseline | stretch;)';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.EXT_ATTRIBUTS IS  '扩展属性';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.CRT_USER_CODE IS  '创建人';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.CRT_ORG_CODE IS  '创建机构';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.CRT_DATE IS  '创建日期';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.UPD_USER_CODE IS  '修改人';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.UPD_ORG_CODE IS  '修改机构';
COMMENT ON COLUMN DEV_ANALYSIS_ITEM_INFO.UPD_DATE IS  '修改日期';


